### ISSUE TITLE
Javascript dynamic nav text color

### ISSUE THREAD

**Issue by robinmetral** [wikitongues/wikitongues-website#5]
We need the navigation links text to be black on most pages, but to be white when the page starts with a `.banner` hero image.

We can unfortunately not so this in pure CSS (I tried but failed).

The layouts seem a bit tricky to tamper with because the nav is included as `header.php` and the (occasional) banner is on the specific page template (for example `front-page.php`). It's hard to relate the two of them (or maybe in PHP?)

One option I see remaining would be using Javascript. Do you know how to do something like this?

**Comment by robinmetral** [comment]
Assigning custom classes to elements using Javascript would also be useful to create different backgrounds depending on the page template.

We could give classes to the <body> element (ex body.homepage) and then use them to add various colored backgrounds as seen in the mockups (using `background: linear-gradient();`)

**Comment by bogreudell** [comment]
This should be done in PHP, I'll take care of it :)

**Comment by robinmetral** [comment]
Working on this!

**Comment by robinmetral** [comment]
I tried but failed. PHP is more difficult than I thought :stuck_out_tongue: 

Please add an additional class to the `nav` element (something like `nav.has-banner` if the page has a banner (the banner is `div.wt_banner`).

**Comment by bogreudell** [comment]
@robinmetral I just realized that there's a much easier way to do this. WP assigns template-specific classes to the <body> element. Homepage is body.home, for instance, and Projects is body.page-template-template-projects. Since certain templates will always have a banner, you can just add to layouts.styl that header on those templates will be white, whereas templates on other pages will be black ☺️

**Comment by robinmetral** [comment]
Great! Done :slightly_smiling_face:
